[tools]
go                     = "latest"
golangci-lint          = "latest"
hugo                   = "latest"
node                   = "lts"
"npm:cspell"           = "latest"
"npm:markdownlint-cli" = "latest"
taplo                  = "latest"

[settings]
experimental = true
lockfile     = true

[hooks]
enter = 'npm install'

[tasks.build]
description = "Build Site"
sources = ["hugo.toml", "assets/**/*", "content/**/*", "data/**/*", "layouts/**/*"]
outputs = ['public/**/*']
quiet = true
alias = "b"
run = """
echo "🍳 Generating site"
hugo --gc --minify -d public
"""

[tasks.check]
description = "Run all checks"
depends     = ["format:check", "lint", "spell"]

[tasks.clean]
description = "Clean built site"
quiet = true
run = """
echo "🧹 Cleaning old build"
rm -rf public resources .hugo_build.lock
"""

[tasks.format]
description = "Format files"
depends     = ["format:go", "format:toml"]
run         = 'npx prettier --write .'

[tasks."format:check"]
description = "Check formatting"
depends     = ["format:go:check", "format:toml:check"]
run         = 'npx prettier --check .'

[tasks."format:go"]
description = "Format Go files"
run         = 'gofmt -w .'

[tasks."format:go:check"]
description = "Check Go formatting"
run         = 'test -z "$(gofmt -l .)"'

[tasks."format:toml"]
description = "Format TOML files"
run         = 'taplo format'

[tasks."format:toml:check"]
description = "Check TOML formatting"
run         = 'taplo format --check'

[tasks."github-data"]
description = "Fetch GitHub data for site"
sources     = ["github.go"]
outputs     = ["data/github.json"]
run         = 'go run github.go -user butlerx -output data/github.json'

[tasks.lint]
description = "Run all linters"
depends     = ["lint:css", "lint:go", "lint:markdown"]

[tasks."lint:css"]
description = "Run CSS linter"
quiet = true
run = """
echo "🍜 Testing CSS"
npx stylelint "assets/css/**/*.css"
"""

[tasks."lint:go"]
description = "Run Go linter"
run         = "golangci-lint run --timeout 5m github.go"

[tasks."lint:markdown"]
description = "Run markdown linter"
quiet = true
run = """
echo "🍜 Testing Markdown"
markdownlint "content"
"""

[tasks.serve]
description = "Run development server in debug mode"
run         = 'hugo server -D -w'

[tasks.spell]
description = "Check spelling"
quiet = true
run = """
echo "🔤 Checking Spelling"
cspell "content/**/*.md"
"""
