baseURL = "/"
languageCode = "en-us"
title = "Cian Butler"
pygmentsCodeFences = true
sectionPagesMenu = "main"

[pagination]
disableAliases = false
pagerSize = 5
path = 'page'

[outputs]
home = ["HTML", "RSS", "MANIFEST"]
page = ["HTML"]

[outputFormats]
[outputFormats.manifest]
name = "manifest"
baseName = "manifest"
mediaType = "application/json"
notAlternative = "true"

[params]
description = "Open Source Developer and SRE"
email = "butlerx@notthe.cloud"
repo = "butlerx/cianbutler.ie"
mastodonUser = "butlerx"
mastodonHost = "mastodon.ie"
title = "Cian Butler, SRE"
theme = "#e7e7e7"

[params.author]
name = "Cian Butler"

[taxonomies]
series = "series"
tag = "tags"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
