[build]
  base    = ""
  command = "make build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-checklinks"
[[plugins]]
  package = "netlify-plugin-a11y"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.89
    accessibility = 0.8
    best-practices = 0.9
    seo = 0.8
    pwa = 0.4
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-no-more-404"
  [plugins.inputs]
    on404 = "error"
