[build]
  base    = ""
  command = "yarn build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-checklinks"
