baseURL = "https://cianbutler.ie/"
languageCode = "en-us"
title = "Cian Butler"
sectionPagesMenu = "main"

[Params]
  Description = "Cian Butler, open source developer and SRE"
  favicon = "images/favicon.ico"
  avatar = "me.png"
  icon = "images/me"
  author = "Cian Butler"
  repo = "butlerx/cv"

[Params.social.twitter]
  icon = "twitter"
  user = "cianbutlerx"
[Params.social.github]
  icon = "github-alt"
  user = "butlerx"
[Params.social.email]
  icon = "envelope"
  address = "butlerx@notthe.cloud"
[Params.social.linkedin]
  icon = "linkedin"
  user = "butlerx"
