baseURL = "https://cian.notthe.cloud/"
languageCode = "en-us"
title = "Not the Cloud"
sectionPagesMenu = "main"

[Params]
  Description = "A Place to put projects info, with a meh title i like."
  favicon = "images/favicon.ico"
  avatar = "me.png"
  icon = "images/me"
  author = "Cian Butler"
  repo = "butlerx/cv"

[Params.social.twitter]
  icon = "twitter"
  user = "cianbutlerx"
[Params.social.mastodon]
  icon = "retweet"
  user = "butlerx"
  host = "mastodon.redbrick.dcu.ie"
[Params.social.github]
  icon = "github-alt"
  user = "butlerx"
[Params.social.email]
  icon = "envelope"
  address = "butlerx@notthe.cloud"
[Params.social.linkedin]
  icon = "linkedin"
  user = "butlerx"
