baseURL = "cian.notthe.cloud"
languageCode = "en-us"
title = "Cian Butler"
cleandestinationdir = true

[Params]
title = "Cian Butler"

[[menu.main]]
  name = "Me"
  url = "me"

[[social]]
  icon = "twitter"
  link = "https://twitter.com/cianbutlerx"
  medium = "Twitter"
[[social]]
  icon = "retweet"
  link = "https://mastodon.redbrick.dcu.ie/@butlerx"
  medium = "Mastodon"
[[social]]
  icon = "github-alt"
  link = "https://github.com/butlerx/"
  medium = "Github"
[[social]]
  icon = "envelope"
  link = "mailto:butlerx@notthe.cloud"
  medium = "Email"
