baseURL = "cian.notthe.cloud"
languageCode = "en-us"
title = "Not the Cloud"
sectionPagesMenu = "main"

[Params]
  Description = "A Place to put projects info, with a meh title i like."
  twitter = "cianbutlerx"
  favicon = "favicon.ico"
  avatar = "me.png"
  author = "Cian Butler"
  email = "butlerx@notthe.cloud"
  repo = "butlerx/cv"

[[Params.social]]
  icon = "twitter"
  link = "https://twitter.com/cianbutlerx"
  medium = "Twitter"
[[Params.social]]
  icon = "retweet"
  link = "https://mastodon.redbrick.dcu.ie/@butlerx"
  medium = "Mastodon"
[[Params.social]]
  icon = "github-alt"
  link = "https://github.com/butlerx/"
  medium = "Github"
[[Params.social]]
  icon = "envelope"
  link = "mailto:butlerx@notthe.cloud"
  medium = "Email"
