name: Rebuild Github data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
jobs:
  githubData:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build data/github.json
        run: deno run --allow-env --allow-net --allow-write github.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prettify code
        uses: actionsx/prettier@v3
        with:
          args: --write data
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Rebuild data/github.json
