name: Rebuild Github data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
jobs:
  githubData:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: npm install
      - name: Install git-emoji
        run: |-
          wget https://raw.githubusercontent.com/butlerx/git-emoji/master/hooks/commit-msg -O .git/hooks/commit-msg
          chmod +x .git/hooks/commit-msg
      - name: Build data/github.json
        run: mise run github-data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format data
        run: mise run format
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Rebuild data/github.json
